//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang_63132681.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        [DisplayName("Mã Khách Hàng")]
        public int MaKhachHang { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        [DisplayName("Họ và tên")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Điện Thoại")]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Số điện thoại phải gồm 10 số.")]
        public string DienThoai { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [DisplayName("Mật Khẩu")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Mật khẩu phải từ 6 đến 20 ký tự.")]
        public string MatKhau { get; set; }
        [DisplayName("Xác Nhận Mật Khẩu")]
        public string XacNhanMatKhau { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
