//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang_63132681.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSanPham()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [DisplayName("Mã Loại Sản Phẩm")]
        [Required(ErrorMessage = "Mã Loại sản phẩm không được để trống")]
        public string MaLoaiSanPham { get; set; }
        [DisplayName("Tên Loại Sản Phẩm")]
        [Required(ErrorMessage = "Tên loại sản phẩm không được để trống")]
        public string TenLoaiSanPham { get; set; }
        [DisplayName("Ảnh Loại Sản Phẩm")]
        public string AnhLoaiSP { get; set; }
        [Required(ErrorMessage = "Mô tả không được để trống")]
        [DisplayName("Mô Tả")]
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
