//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang_63132681.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
        [DisplayName("Mã Nhân Viên")]
      
        
        
        public int MaNhanVien { get; set; }
        [DisplayName("Họ Tên Nhân Viên")]
        [Required(ErrorMessage = "Têm Nhân Viên không được để trống")]
        public string HoTen { get; set; }
        [DisplayName("Ảnh Nhân Viên")]
        public string AnhNhanVien { get; set; }
        [DisplayName("Điện Thoại")]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Số điện thoại phải gồm 10 số.")]
        public string DienThoai { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được để trống")]
        [DisplayName("Địa Chỉ")]
        public string DiaChi { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Mật khẩu phải từ 6 đến 20 ký tự.")]
        [DisplayName("Mật Khẩu")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Quyền Truy Cập  không được để trống")]
        [DisplayName("Quyền Truy Cập")]
        public string QuyenTruyCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
